### ISSUE TITLE
Artificially generated triplets?

### ISSUE THREAD

**Issue by MiroFurtado** [Unbabel/OpenKiwi#28] opened 2019-06-06 22:40 UTC
Do you all have any plans to make the artificially generated training corpus referenced in your paper available publicly? I might be missing it, but I can't find that data on the repo.

I would like to reproduce the Openkiwi results from scratch, but without this , the dataset is very small.

Thanks!

**Comment by MiroFurtado** [comment] 2019-06-06 22:41
oops - didn't mean to tag as bug!

**Comment by captainvera** [comment] 2019-06-11 17:21
Hello @MiroFurtado

First of all, thanks for your interest in OpenKiwi! 

You are right, the artificially generated training corpus (with ~500k triplets) we reference on our paper is **not** available publicly. It is based on the in-domain German corpus provided by WMT which is what we used to pre-train the predictors. We provide a link for this corpus in our Quickstart section [here](https://unbabel.github.io/OpenKiwi/quickstart.html).

We had no plans for making this data available, but you raise a valid concern for reproducibility. 
Thanks for bringing this to our attention! 
We have to take some things into consideration but we will get back to you soon!

**Comment by MiroFurtado** [comment] 2019-06-11 18:25
Great! Let me know what you end up deciding.

**Comment by trenous** [comment] 2019-06-17 11:03
Actually the triplets are available in the data section on [this site](https://marian-nmt.github.io/examples/postedit/). The download there contains both the 500k triplets we used, and a larger corpus of 4 million triplets.

To generate QE tags from the triplets, you can follow the instructions in [this repository](https://github.com/Unbabel/word-level-qe-corpus-builder)

**Comment by trenous** [comment] 2019-06-18 10:25
Hello @MiroFurtado ,

I uploaded the missing tags and sentence scores for the artificial roundtrip data to our [releases](https://github.com/Unbabel/OpenKiwi/releases/download/0.1.1/500k.zip).

If you wanted to recreate these files using the repository I posted in my previous comment, you need to train a FastAlign model, which is used to generate the source tags. We trained FastAlign on the English-German indomain corpus of 3 million parallel sentences, if you use a different FastAlign model you will get slightly different source tags.

**Comment by captainvera** [comment] 2019-06-18 10:39
Closing this since the issue has been solved.

Feel free to reopen if you have any further questions @MiroFurtado

**Closed by captainvera** 2019-06-18 10:39 UTC
Labels: question
