### ISSUE TITLE
Failed to rerun predictor model

### ISSUE THREAD

**Issue by damyana79** [Unbabel/OpenKiwi#35] opened 2019-06-28 15:31 UTC
**Describe the bug**

When I try to rerun an already trained predictor model I get: 

~/.local/lib/python3.5/site-packages/kiwi/lib/train.py", line 187, in run
    logger.info(str(trainer.model))

 AttributeError: 'NoneType' object has no attribute 'model'

**To Reproduce**
I have trained the predictor model with the default configuration for 6 epochs and it ran fine. Then I tried to rerun it for a few more epochs with the following changed arguments:

+ checkpoint-early-stop-patience:20
+ run-uuid: 33939be51e8a4f04a9f485142e16000d   
+ resume: true

I retrieved the run-uuid from the runs/model_name/output.log file:
This is run ID: 33939be51e8a4f04a9f485142e16000d
Is this the correct one? Are there any further arguments that need to be provided in order to rerun/train further a model?

I will also attach my config file.

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 19.04
[train_config.txt](https://github.com/Unbabel/OpenKiwi/files/3339861/train_config.txt)

 - OpenKiwi version 0.1.1
 - Python version 3.5

**Comment by captainvera** [comment] 2019-07-01 15:45
Hello @damyana79

Thanks for reporting this issue! I'll look into this and get back to you soon.

**Comment by captainvera** [comment] 2019-07-04 09:13
Hey @damyana79 

I haven't been able to reproduce your issue with resuming. It seems to be happening because Kiwi cannot load the trainer and model from your previous run.
This means that for some reason it is looking in the wrong place. Would you mind sharing your output.log? This should be stored in the same folder as your model

**Comment by captainvera** [comment] 2019-07-04 09:26
However, I'll take this chance to clarify some details about model re-training. I believe our documentation is slightly misleading as it is. 

There are two ways to continue to train a model: 1 - Resuming and 2 - Loading

**Resuming**
When you are resuming, you are retrieving the previous state of the trainer. This includes everything related to the training process including, for example, optimizer parameters. The use case for this is things like preemptible servers where your training might stop and you might need to resume from the latest checkpoint. As such, you have to increase your total number of epochs if you want to continue training.

When resuming, Kiwi will first look for the trainer in your `output-dir` and then in `runs/uuid` if you don't specify the `output-dir`. In your case, since you state the `output-dir` there's no need to state the `run-uuid`.

**Loading**
On the other hand, if you just want to load model weights and continue training with new optimizer/trainer parameters you can just pass the `load-model` flag pointing at the model you'd like to load.

**Comment by captainvera** [comment] 2019-07-09 14:22
This behaviour as been clarified and improved with #36. 

I will now close this. Feel free to re-open if your problem continues!

**Closed by captainvera** 2019-07-09 14:22 UTC
Labels: bug
