### ISSUE TITLE
GPU ID

### ISSUE THREAD

**Issue by Parkchanjun** [Unbabel/OpenKiwi#31] opened 2019-06-20 06:00 UTC
I have some Qustion

I set the
gpu-id: "0 1 2 3 4 5 6 7"

But error is occurred
kiwi train: error: argument --gpu-id: invalid int value: '0 1 2 3 4 5 6 7'

How to set the multi GPU ID in OpenKIWI?

**Comment by trenous** [comment] 2019-06-20 16:02
Multi GPU training is not yet supported in OpenKiwi, that's why you get that error.

**Comment by captainvera** [comment] 2019-06-25 14:00
I'm closing this as it is not a bug. 

I'm redirecting the requests to implement Multi-GPU training to #33

**Closed by captainvera** 2019-06-25 14:00 UTC
Labels: bug
