### ISSUE TITLE
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by Shannen3206** [Unbabel/OpenKiwi#75] opened 2020-10-21 05:09 UTC
**Describe the bug**
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**To Reproduce**
1. Creat a new file: run.py
```
from kiwi.lib.train import train_from_file
run_info = train_from_file('config/bert.yaml')
```
and then execute this program
2、See error
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Expected behavior**
I hope to pass the type check when the parameter is initialized

**Screenshots**
https://github.com/Shannen3206/csn/blob/master/error.png

**Environment (please complete the following information):**
 - OS: Linux
 - OpenKiwi version： 2.0.0
 - Python version：3.6.9

**Comment by captainvera** [comment] 2020-10-21 13:50
Hello @Shannen3206,

How did you install kiwi 2.0.0 on python 3.6.9?  Kiwi 2.0.0 requires python >=3.7

I tried reproducing your code on 3.7 and found another bug, being fixed in #76 which should be merged shortly.

Let me know if you have any other problems

**Comment by captainvera** [comment] 2020-10-21 14:06
I see you can install openkiwi on 3.6 using pip, but it is unfortunately not supported.

**Comment by Shannen3206** [comment] 2020-10-21 15:10
Python3.7 version solves the previous problem. Thank you very much!

**Comment by daandouwe** [comment] 2020-10-27 14:18
Issue closed because it has been resolved.

**Closed by daandouwe** 2020-10-27 14:18 UTC
Labels: bug
