### ISSUE TITLE
Error training estimator model

### ISSUE THREAD

**Issue by HqWu-HITCS** [Unbabel/OpenKiwi#18] opened 2019-03-20 07:41 UTC
Hi~, thank you for releasing the code.

I got error when i training the estimator model( kiwi train --config experiments/train_estimator.yaml) as follow:

Traceback (most recent call last):
  File "/home/***/anaconda3/bin/kiwi", line 11, in <module>
    sys.exit(main())
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/__main__.py", line 22, in main
    return kiwi.cli.main.cli()
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/cli/main.py", line 71, in cli
    train.main(extra_args)
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/cli/pipelines/train.py", line 141, in main
    train.train_from_options(options)
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/lib/train.py", line 123, in train_from_options
    trainer = run(ModelClass, output_dir, pipeline_options, model_options)
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/lib/train.py", line 204, in run
    trainer.run(train_iter, valid_iter, epochs=pipeline_options.epochs)
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/trainers/trainer.py", line 75, in run
    self.train_epoch(train_iterator, valid_iterator)
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/trainers/trainer.py", line 95, in train_epoch
    outputs = self.train_step(batch)
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/trainers/trainer.py", line 139, in train_step
    model_out = self.model(batch)
  File "/home/***/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/models/predictor_estimator.py", line 349, in forward
    sentence_input = self.make_sentence_input(h_tgt, h_src)
  File "/home/***/anaconda3/lib/python3.6/site-packages/kiwi/models/predictor_estimator.py", line 418, in make_sentence_input
    h = h_tgt[0] if h_tgt else h_src[0]
TypeError: 'NoneType' object is not subscriptable

I am training the estimator model only on sentence level QE data, and i have checked my data. here is my setting:

token-level: True
sentence-level: True
sentence-ll: False
binary-level: False
predict-target: False
predict-source: False
predict-gaps: false 

Could you give me some advice for solving this error? Thank you very much！

**Comment by captainvera** [comment] 2019-03-20 16:21
Hey @HqWu-HITCS, thanks for experimenting with OpenKiwi.

I managed to reproduce your error. 
The problem is that we hadn't considered the possibility of training the Estimator model **solely** for sentence level. A fix has been proposed in #19 and should be merged shortly.

**Comment by captainvera** [comment] 2019-03-22 14:44
This has now been merged. I will close the issue. 
Feel free to re-open if you have any issues with the newest master.

**Closed by captainvera** 2019-03-22 14:44 UTC
Labels: bug

**Comment by HqWu-HITCS** [comment] 2019-03-22 15:57
> This has now been merged. I will close the issue.
> Feel free to re-open if you have any issues with the newest master.

Thank you very much~

**Comment by VictorLi2017** [comment] 2019-04-25 07:12
@HqWu-HITCS 你好！你之前提出的这个问题解决了吗？我现在训练estimator，也遇到了你同样的问题，TypeError: 'NoneType' object is not subscriptable，一直无法进行下去。。。

**Comment by HqWu-HITCS** [comment] 2019-04-25 09:42
> @HqWu-HITCS 你好！你之前提出的这个问题解决了吗？我现在训练estimator，也遇到了你同样的问题，TypeError: 'NoneType' object is not subscriptable，一直无法进行下去。。。

作者后来修改了这个bug，更新代码后就好使了。

**Comment by VictorLi2017** [comment] 2019-04-25 09:47
> > @HqWu-HITCS 你好！你之前提出的这个问题解决了吗？我现在训练estimator，也遇到了你同样的问题，TypeError: 'NoneType' object is not subscriptable，一直无法进行下去。。。
> 
> 作者后来修改了这个bug，更新代码后就好使了。

我用了最新版本的repo, 无论WMT的官方语料还是CWMT的汉英语料，训练句子级别的estimator总是不行。你用的什么语种的语料呢？方便分享一份你的config.yaml吗？非常感谢！

**Comment by HqWu-HITCS** [comment] 2019-04-25 10:01
> > > @HqWu-HITCS 你好！你之前提出的这个问题解决了吗？我现在训练estimator，也遇到了你同样的问题，TypeError: 'NoneType' object is not subscriptable，一直无法进行下去。。。
> > 
> > 
> > 作者后来修改了这个bug，更新代码后就好使了。
> 
> 我用了最新版本的repo, 无论WMT的官方语料还是CWMT的汉英语料，训练句子级别的estimator总是不行。你用的什么语种的语料呢？方便分享一份你的config.yaml吗？非常感谢！

WMT和CWMT我都用过，都没问题，以下是我的config

### Train Predictor Estimator ###

model: estimator
output-dir: runs/estimator_zhen_256

#### MODEL SPECIFIC OPTS ####

## ESTIMATOR ##

hidden-est: 256
rnn-layers-est: 2
dropout-est: 0.0
mlp-est: True

# Multitask Learning Settings #

token-level: True
sentence-level: True
sentence-ll: False
binary-level: False

# WMT 18 Format Settings #24 

predict-target: False
predict-source: False
predict-gaps: false

### GENERAL OPTS ###
gpu-id: 1

### TRAIN OPTS ###
epochs: 15
checkpoint-validation-steps: 0
checkpoint-save: true
checkpoint-keep-only-best: 3
checkpoint-early-stop-patience: 0
log-interval: 100
learning-rate: 2e-3

train-batch-size: 32
valid-batch-size: 32

### LOADING ###

load-pred-target: runs/predictor/step_310000/model.torch

source-max-length: 60
source-min-length: 1
target-max-length: 60
target-min-length: 1

###  DATA ###

# Set to True to use target_tags in WMT18 format

train-source: /home/hqwu/QE/qebrain/data/qe/train.src
train-target: /home/hqwu/QE/qebrain/data/qe/train.trg
train-pe: /home/hqwu/QE/qebrain/data/qe/train.pe
train-sentence-scores: /home/hqwu/QE/qebrain/data/qe/train.hter


valid-source: /home/.../QE/qebrain/data/qe/dev.src
valid-target: /home/.../QE/qebrain/data/qe/dev.trg
valid-pe: /home/.../QE/qebrain/data/qe/dev.pe
valid-sentence-scores: /home/.../QE/qebrain/data/qe/dev.hter

**Comment by VictorLi2017** [comment] 2019-04-26 05:20
@HqWu-HITCS 谢谢～ 我新建了一个虚拟环境，重装了openkiwi,用你的config重新跑数据，还是卡在train_estimator了。错误依然还是NoneType object is not subscriptable……

**Comment by VictorLi2017** [comment] 2019-04-26 07:41
@HqWu-HITCS 不好意思，再次打扰了~ 请问你后来用最新的repo把**整个QE的流程**都跑通了是吗？你是用哪种方式跑的？是命令行方式`kiwi train --config=train_estimator.yaml`
还是在py文件里调用的呢？
`import kiwi
estimator_config = 'train_estimator.yaml'
kiwi.train(estimator_config)`

我用了两种方式，始终都跑不通……

**Comment by HqWu-HITCS** [comment] 2019-04-26 07:45
我是用命令行跑的，都跑通了，但我是先跑完了predictor，后来发现不对，于是在上边提了issue，后来作者给更新了代码，我就也一样更新了下我本地的代码，接着跑的estimator，然后就可以了~



wuhuanqin@foxmail.com
 
From: Hongzheng Li
Date: 2019-04-26 15:41
To: Unbabel/OpenKiwi
CC: hqWu; Mention
Subject: Re: [Unbabel/OpenKiwi] Error training estimator model (#18)
@HqWu-HITCS 不好意思，再次打扰了~ 请问你后来用最新的repo把整个QE的流程都跑通了是吗？你是用哪种方式跑的？是命令行方式kiwi train --config=train_estimator.yaml
还是在py文件里调用的呢？
import kiwi estimator_config = 'train_estimator.yaml' kiwi.train(estimator_config)
我用了两种方式，始终都跑不通……

**Comment by Zachary-YL** [comment] 2019-04-26 07:47
你好 @HqWu-HITCS ，我也正在跑`Predictor-Estimator`模型，训练部分没有问题，但是到了预测的那一步，发生了错误：

2019-04-22 07:19:37.521 [kiwi.lib.predict setup:159] {'batch_size': 64,
'config': 'experiments_sl/predict_estimator.yaml',
'debug': False,
'experiment_name': 'EN-ZH Pretrain Predictor',
'gpu_id': None,
'load_data': None,
'load_model': 'runs/0/464dc10bfc174ac79ca082eae0dea352/best_model.torch',
'load_vocab': None,
'log_interval': 100,
'mlflow_always_log_artifacts': False,
'mlflow_tracking_uri': 'mlruns/',
'model': 'estimator',
'output_dir': 'predictions/predest/ccmt/en_zh',
'quiet': False,
'run_uuid': None,
'save_config': None,
'save_data': None,
'seed': 42}
2019-04-22 07:19:37.521 [kiwi.lib.predict setup:160] Local output directory is: predictions/predest/ccmt/en_zh
2019-04-22 07:19:37.521 [kiwi.lib.predict run:100] Predict with the PredEst (Predictor-Estimator) model
Traceback (most recent call last):
File "/home2/zyl/anaconda3/envs/openkiwi/bin/kiwi", line 10, in 
sys.exit(main())
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/main.py", line 22, in main
return kiwi.cli.main.cli()
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/cli/main.py", line 73, in cli
predict.main(extra_args)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/cli/pipelines/predict.py", line 56, in main
predict.predict_from_options(options)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/lib/predict.py", line 54, in predict_from_options
run(options.model_api, output_dir, options.pipeline, options.model)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/lib/predict.py", line 113, in run
model = Model.create_from_file(pipeline_opts.load_model)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/models/model.py", line 214, in create_from_file
model = Model.subclasses[model_name].from_dict(model_dict)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/models/model.py", line 235, in from_dict
model.load_state_dict(class_dict[const.STATE_DICT])
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
self.class.name, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Estimator:
Unexpected key(s) in state_dict: "predictor_tgt.W2", "predictor_tgt.V", "predictor_tgt.C", "predictor_tgt.S", "predictor_tgt.attention.scorer.layers.0.0.weight", "predictor_tgt.attention.scorer.layers.0.0.bias", "predictor_tgt.attention.scorer.layers.1.0.weight", "predictor_tgt.attention.scorer.layers.1.0.bias", "predictor_tgt.embedding_source.weight", "predictor_tgt.embedding_target.weight", "predictor_tgt.lstm_source.weight_ih_l0", "predictor_tgt.lstm_source.weight_hh_l0", "predictor_tgt.lstm_source.bias_ih_l0", "predictor_tgt.lstm_source.bias_hh_l0", "predictor_tgt.lstm_source.weight_ih_l0_reverse", "predictor_tgt.lstm_source.weight_hh_l0_reverse", "predictor_tgt.lstm_source.bias_ih_l0_reverse", "predictor_tgt.lstm_source.bias_hh_l0_reverse", "predictor_tgt.lstm_source.weight_ih_l1", "predictor_tgt.lstm_source.weight_hh_l1", "predictor_tgt.lstm_source.bias_ih_l1", "predictor_tgt.lstm_source.bias_hh_l1", "predictor_tgt.lstm_source.weight_ih_l1_reverse", "predictor_tgt.lstm_source.weight_hh_l1_reverse", "predictor_tgt.lstm_source.bias_ih_l1_reverse", "predictor_tgt.lstm_source.bias_hh_l1_reverse", "predictor_tgt.forward_target.weight_ih_l0", "predictor_tgt.forward_target.weight_hh_l0", "predictor_tgt.forward_target.bias_ih_l0", "predictor_tgt.forward_target.bias_hh_l0", "predictor_tgt.forward_target.weight_ih_l1", "predictor_tgt.forward_target.weight_hh_l1", "predictor_tgt.forward_target.bias_ih_l1", "predictor_tgt.forward_target.bias_hh_l1", "predictor_tgt.backward_target.weight_ih_l0", "predictor_tgt.backward_target.weight_hh_l0", "predictor_tgt.backward_target.bias_ih_l0", "predictor_tgt.backward_target.bias_hh_l0", "predictor_tgt.backward_target.weight_ih_l1", "predictor_tgt.backward_target.weight_hh_l1", "predictor_tgt.backward_target.bias_ih_l1", "predictor_tgt.backward_target.bias_hh_l1", "predictor_tgt.W1.weight".

您有遇到这个问题吗？能不能分享一下您的`predict_estimator.yaml`文件？

**Comment by HqWu-HITCS** [comment] 2019-04-26 07:50
没有遇到这个问题，我的predict_estimator.yaml 如下：

load-model: runs/estimator/best_model.torch
output-dir: test_data/estimator_test

sentence-level: true

gpu-id: 0

model: estimator

test-source: /home/.../QE/.../data/qe/.../test.src
test-target: /home/.../QE/.../data/qe/.../test.trg



wuhuanqin@foxmail.com
 
From: Zachary-YL
Date: 2019-04-26 15:47
To: Unbabel/OpenKiwi
CC: hqWu; Mention
Subject: Re: [Unbabel/OpenKiwi] Error training estimator model (#18)
你好 @HqWu-HITCS ，我也正在跑Predictor-Estimator模型，训练部分没有问题，但是到了预测的那一步，发生了错误：
2019-04-22 07:19:37.521 [kiwi.lib.predict setup:159] {'batch_size': 64,
'config': 'experiments_sl/predict_estimator.yaml',
'debug': False,
'experiment_name': 'EN-ZH Pretrain Predictor',
'gpu_id': None,
'load_data': None,
'load_model': 'runs/0/464dc10bfc174ac79ca082eae0dea352/best_model.torch',
'load_vocab': None,
'log_interval': 100,
'mlflow_always_log_artifacts': False,
'mlflow_tracking_uri': 'mlruns/',
'model': 'estimator',
'output_dir': 'predictions/predest/ccmt/en_zh',
'quiet': False,
'run_uuid': None,
'save_config': None,
'save_data': None,
'seed': 42}
2019-04-22 07:19:37.521 [kiwi.lib.predict setup:160] Local output directory is: predictions/predest/ccmt/en_zh
2019-04-22 07:19:37.521 [kiwi.lib.predict run:100] Predict with the PredEst (Predictor-Estimator) model
Traceback (most recent call last):
File "/home2/zyl/anaconda3/envs/openkiwi/bin/kiwi", line 10, in
sys.exit(main())
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/main.py", line 22, in main
return kiwi.cli.main.cli()
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/cli/main.py", line 73, in cli
predict.main(extra_args)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/cli/pipelines/predict.py", line 56, in main
predict.predict_from_options(options)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/lib/predict.py", line 54, in predict_from_options
run(options.model_api, output_dir, options.pipeline, options.model)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/lib/predict.py", line 113, in run
model = Model.create_from_file(pipeline_opts.load_model)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/models/model.py", line 214, in create_from_file
model = Model.subclasses[model_name].from_dict(model_dict)
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/kiwi/models/model.py", line 235, in from_dict
model.load_state_dict(class_dict[const.STATE_DICT])
File "/home2/zyl/anaconda3/envs/openkiwi/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
self.class.name, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Estimator:
Unexpected key(s) in state_dict: "predictor_tgt.W2", "predictor_tgt.V", "predictor_tgt.C", "predictor_tgt.S", "predictor_tgt.attention.scorer.layers.0.0.weight", "predictor_tgt.attention.scorer.layers.0.0.bias", "predictor_tgt.attention.scorer.layers.1.0.weight", "predictor_tgt.attention.scorer.layers.1.0.bias", "predictor_tgt.embedding_source.weight", "predictor_tgt.embedding_target.weight", "predictor_tgt.lstm_source.weight_ih_l0", "predictor_tgt.lstm_source.weight_hh_l0", "predictor_tgt.lstm_source.bias_ih_l0", "predictor_tgt.lstm_source.bias_hh_l0", "predictor_tgt.lstm_source.weight_ih_l0_reverse", "predictor_tgt.lstm_source.weight_hh_l0_reverse", "predictor_tgt.lstm_source.bias_ih_l0_reverse", "predictor_tgt.lstm_source.bias_hh_l0_reverse", "predictor_tgt.lstm_source.weight_ih_l1", "predictor_tgt.lstm_source.weight_hh_l1", "predictor_tgt.lstm_source.bias_ih_l1", "predictor_tgt.lstm_source.bias_hh_l1", "predictor_tgt.lstm_source.weight_ih_l1_reverse", "predictor_tgt.lstm_source.weight_hh_l1_reverse", "predictor_tgt.lstm_source.bias_ih_l1_reverse", "predictor_tgt.lstm_source.bias_hh_l1_reverse", "predictor_tgt.forward_target.weight_ih_l0", "predictor_tgt.forward_target.weight_hh_l0", "predictor_tgt.forward_target.bias_ih_l0", "predictor_tgt.forward_target.bias_hh_l0", "predictor_tgt.forward_target.weight_ih_l1", "predictor_tgt.forward_target.weight_hh_l1", "predictor_tgt.forward_target.bias_ih_l1", "predictor_tgt.forward_target.bias_hh_l1", "predictor_tgt.backward_target.weight_ih_l0", "predictor_tgt.backward_target.weight_hh_l0", "predictor_tgt.backward_target.bias_ih_l0", "predictor_tgt.backward_target.bias_hh_l0", "predictor_tgt.backward_target.weight_ih_l1", "predictor_tgt.backward_target.weight_hh_l1", "predictor_tgt.backward_target.bias_ih_l1", "predictor_tgt.backward_target.bias_hh_l1", "predictor_tgt.W1.weight".
您有遇到这个问题吗？能不能分享一下您的predict_estimator.yaml文件？

**Comment by VictorLi2017** [comment] 2019-04-26 08:09
> 我是用命令行跑的，都跑通了，但我是先跑完了predictor，后来发现不对，于是在上边提了issue，后来作者给更新了代码，我就也一样更新了下我本地的代码，接着跑的estimator，然后就可以了~ wuhuanqin@foxmail.com From: Hongzheng Li Date: 2019-04-26 15:41 To: Unbabel/OpenKiwi CC: hqWu; Mention Subject: Re: [Unbabel/OpenKiwi] Error training estimator model (#18) @HqWu-HITCS 不好意思，再次打扰了~ 请问你后来用最新的repo把整个QE的流程都跑通了是吗？你是用哪种方式跑的？是命令行方式kiwi train --config=train_estimator.yaml 还是在py文件里调用的呢？ import kiwi estimator_config = 'train_estimator.yaml' kiwi.train(estimator_config) 我用了两种方式，始终都跑不通…… — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

你能再给我一份**train_predictor.yaml**的配置文件吗？多谢多谢！

**Comment by Zachary-YL** [comment] 2019-04-26 12:12
@HqWu-HITCS 你好，能告知一下你运行Openkiwi的Python版本吗？

**Comment by captainvera** [comment] 2019-04-26 15:52
Hey guys, could you please write in English so we understand what is going on and are able to help?

Thanks

**Comment by VictorLi2017** [comment] 2019-04-26 16:06
> Hey guys, could you please write in English so we understand what is going on and are able to help?
> 
> Thanks

@captainvera Sorry for that. We've been talking about the errors happened during the `train_estimator` and next `predictor` step, as discussed in #22 and #23, for #22 , the error **TypeError: 'NoneType' object is not subscriptable** always exists, even with the latest repo of the openkiwi toolkit.

**Comment by Zachary-YL** [comment] 2019-04-27 06:38
> Hey guys, could you please write in English so we understand what is going on and are able to help?
> 
> Thanks


Hi @captainvera, as  VictorLi2017 said, I am talking about the errors happened during the `predictor` step, as discussed in #23, the error **Error(s) in loading state_dict for Estimator** always exists.

**Comment by captainvera** [comment] 2019-04-29 13:01
@VictorLi2017 @Zachary-YL  I understand. While it is excellent that you're trying to help each other with the issues, it is more beneficial if you keep it In English so we can all gain from the discussion! :) 

On our end, we apologize but we are currently extremely busy internally. As such we will get back to you in a couple of weeks.
